# Generated by Django 5.0.2 on 2024-02-21 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicineStore', '0002_remove_prescription_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='medicineStore.patient'),
        ),
    ]
